import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  data_freshness: DataFreshness;
  disclaimer: string;
  source_authority: SourceAuthority;
  coverage_gaps: string[];
  ai_disclosure: string;
}

export interface DataFreshness {
  statute_last_updated: string | null;
  case_law_last_sync: string | null;
  staleness_warning: string | null;
}

export interface SourceAuthority {
  primary_source: string;
  authority_level: 'official' | 'community-maintained';
  verification_required: string;
}

export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL ADVICE. This tool is for research purposes only. Always verify citations with official sources (pisrs.si, sodnapraksa.si) before relying on them in legal matters.',
    source_authority: {
      primary_source: 'pisrs.si (PIS — Pravno-informacijski sistem RS) for statutes; sodnapraksa.si for case law',
      authority_level: 'official',
      verification_required: 'ALWAYS cross-check with official sources before using in professional legal work.',
    },
    coverage_gaps: [
      'Full EU directive/regulation text (metadata only)',
      'CJEU case law',
      'Historical statute versions (limited availability)',
      'Legal commentary and annotations',
    ],
    ai_disclosure: 'AI-assisted legal research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.',
  };
}

function getEmptyDataFreshness(): DataFreshness {
  return {
    statute_last_updated: null,
    case_law_last_sync: null,
    staleness_warning: 'Data freshness information unavailable',
  };
}

function getDataFreshness(db: Database): DataFreshness {
  let statuteLastUpdated: string | null = null;
  try {
    const row = db.prepare(`SELECT MAX(last_updated) as max_date FROM legal_documents WHERE type = 'statute' AND last_updated IS NOT NULL`).get() as { max_date: string | null } | undefined;
    statuteLastUpdated = row?.max_date || null;
  } catch { /* ignore */ }

  let caseLawLastSync: string | null = null;
  try {
    const row = db.prepare(`SELECT last_sync_date FROM case_law_sync_metadata WHERE id = 1`).get() as { last_sync_date: string } | undefined;
    caseLawLastSync = row?.last_sync_date || null;
  } catch { /* table might not exist */ }

  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const warnings: string[] = [];

  if (statuteLastUpdated) {
    const ts = new Date(statuteLastUpdated);
    if (ts < thirtyDaysAgo) {
      warnings.push(`Statute data is ${Math.floor((now.getTime() - ts.getTime()) / (24 * 60 * 60 * 1000))} days old`);
    }
  } else {
    warnings.push('Statute update timestamp unavailable');
  }

  if (caseLawLastSync) {
    const ts = new Date(caseLawLastSync);
    if (ts < thirtyDaysAgo) {
      warnings.push(`Case law data is ${Math.floor((now.getTime() - ts.getTime()) / (24 * 60 * 60 * 1000))} days old`);
    }
  }

  return {
    statute_last_updated: statuteLastUpdated,
    case_law_last_sync: caseLawLastSync,
    staleness_warning: warnings.length > 0 ? warnings.join('. ') : null,
  };
}

export interface ToolResponse<T> {
  results: T;
  _metadata: ResponseMetadata;
}
